version: '3.1'
services:
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=emiteai
      - POSTGRES_USER=emiteaishop
      - POSTGRES_DB=emiteai-db